apiVersion: v1
kind: ReplicationController
metadata:
  name: yadav-rc1
spec:
  replicas: 1 #number of pod we want
  template: 
    metadata: # info about kind 
      labels: 
        x: hello 
    spec: # info about your Resources like storage,container,ram,cpu etc
      #nodeSelector: 
      #  kubernetes.io/hostname: aks-agentpool-41845352-vmss000001
      containers: # container info 
      - name: yadavc1 
        image: 0001101988/demoapp:latest # image from docker hub
        ports: # port of app
        - containerPort: 80 # port of app  
        env: 
        - name: AppName
          value: Hello World
